from pathlib import Path
p=Path('/home/ubuntu/projects/depthwizard-b61638c4/index.html')
s=p.read_text()
css='''
.fly-panel{background:rgba(17,27,25,.94);border:1px solid var(--line);box-shadow:0 20px 55px #0003}.fly-canvas-wrap{height:520px;position:relative;overflow:hidden;background:#07100e;touch-action:none}.fly-canvas-wrap canvas{width:100%;height:100%;display:block}.fly-hud{position:absolute;inset:0;pointer-events:none}.fly-readout{position:absolute;background:#09100fcc;border:1px solid #caff5a44;padding:9px 11px}.fly-controls{display:flex;flex-wrap:wrap;gap:8px;align-items:center}.fly-controls .btn{font-size:11px}.fly-progress{height:3px;background:#ffffff12}.fly-progress i{display:block;height:100%;background:var(--lime);width:0%}.fly-corner{position:absolute;width:20px;height:20px;border-color:#caff5a99}.fly-corner.tl{top:18px;left:18px;border-top:1px solid;border-left:1px solid}.fly-corner.tr{top:18px;right:18px;border-top:1px solid;border-right:1px solid}.fly-corner.bl{bottom:18px;left:18px;border-bottom:1px solid;border-left:1px solid}.fly-corner.br{bottom:18px;right:18px;border-bottom:1px solid;border-right:1px solid}
'''
s=s.replace('</style></head>',css+'</style></head>',1)
marker='<div class="grid grid-cols-2 md:grid-cols-4 gap-3"><div class="metric'
viewer='''<div id="flyPanel" class="fly-panel rounded-2xl overflow-hidden mb-5"><div class="px-5 py-4 border-b border-[#253631] flex flex-wrap items-center justify-between gap-3"><div><div class="eyebrow">02A / 3D depth flythrough</div><div class="text-sm font-bold mt-1">Move through the photograph, not just into it.</div></div><div class="flex items-center gap-2"><span id="flyMode" class="mono text-[10px] text-[#879890]">AWAITING DEPTH SCENE</span><button id="flyPlay" class="btn quiet rounded px-3 py-1.5 text-[11px]">▶ Play flythrough</button><button id="flyFullscreen" class="btn quiet rounded px-3 py-1.5 text-[11px]">⛶ Fullscreen</button></div></div><div id="flyWrap" class="fly-canvas-wrap"><canvas id="flyCanvas"></canvas><div class="fly-hud"><div class="fly-corner tl"></div><div class="fly-corner tr"></div><div class="fly-corner bl"></div><div class="fly-corner br"></div><div class="fly-readout left-5 top-5"><div class="eyebrow">Camera pose</div><div id="flyPose" class="mono text-[11px] text-[#edf5ef] mt-1">X 0.00 / Y 0.00 / Z 1.00</div></div><div class="fly-readout right-5 top-5 text-right"><div class="eyebrow">Layer stack</div><div class="mono text-[11px] text-[#caff5a] mt-1">PERSON · MID · FAR</div></div><div class="absolute left-5 bottom-5 mono text-[10px] text-[#879890]">DRAG ROTATE · SCROLL ZOOM · ARROWS MOVE</div></div></div><div class="px-5 py-4 border-t border-[#253631]"><div class="fly-controls"><button id="flyReset" class="btn quiet rounded px-3 py-2">Reset view</button><button id="flyLight" class="btn quiet rounded px-3 py-2">Depth lighting <span id="flyLightState">ON</span></button><span class="mono text-[10px] text-[#879890] ml-auto">PARALLAX <b id="flyParallax" class="text-[#edf5ef]">1.00×</b></span><input id="flyParallaxRange" type="range" min=".3" max="1.8" step=".1" value="1" class="w-24"></div><div class="fly-progress mt-3"><i id="flyProgress"></i></div></div></div>'''
s=s.replace(marker,viewer+marker,1)
needle="data=json;clearInterval(tick);"
s=s.replace(needle,"data=json;clearInterval(tick);initFlythrough(data);",1)
flyjs=r'''
// --- 2.5D depth flythrough -------------------------------------------------
let fly={canvas:null,ctx:null,bg:null,person:null,depth:null,ready:false,playing:false,lighting:true,parallax:1,x:0,y:0,z:1,yaw:0,pitch:0,lastX:0,lastY:0,drag:false,raf:0,started:0};
function flyLoad(url){return new Promise((resolve,reject)=>{const i=new Image();i.crossOrigin='anonymous';i.onload=()=>resolve(i);i.onerror=reject;i.src=url})}
async function initFlythrough(result){try{fly.bg=await flyLoad(result.assets.original_url);fly.person=await flyLoad(result.assets.cutout_url);fly.depth=await flyLoad(result.assets.depth_map_url);fly.canvas=$('flyCanvas');fly.ctx=fly.canvas.getContext('2d');fly.ready=true;$('flyMode').textContent='3 LAYERS · READY';$('flyMode').style.color='var(--lime)';flyReset();flyResize();if(!fly.raf)fly.raf=requestAnimationFrame(flyFrame);log('3D depth scene assembled · foreground/background layers')}catch(e){$('flyMode').textContent='DEPTH SCENE UNAVAILABLE';log('Flythrough error: '+e.message)}}
function flyResize(){if(!fly.canvas)return;const r=fly.canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);fly.canvas.width=Math.max(1,Math.floor(r.width*d));fly.canvas.height=Math.max(1,Math.floor(r.height*d));fly.ctx.setTransform(d,0,0,d,0,0)}
function flyReset(){fly.x=0;fly.y=0;fly.z=1;fly.yaw=0;fly.pitch=0;flyUpdateHud()}
function flyUpdateHud(){$('flyPose').textContent=`X ${fly.x.toFixed(2)} / Y ${fly.y.toFixed(2)} / Z ${fly.z.toFixed(2)}`;$('flyParallax').textContent=fly.parallax.toFixed(1)+'×';$('flyProgress').style.width=((fly.started%9000)/9000*100)+'%'}
function fitImage(ctx,img,w,h,scale=1,dx=0,dy=0){const ratio=Math.max(w/img.width,h/img.height)*scale;const iw=img.width*ratio,ih=img.height*ratio;ctx.drawImage(img,(w-iw)/2+dx,(h-ih)/2+dy,iw,ih)}
function flyFrame(t){fly.raf=requestAnimationFrame(flyFrame);if(!fly.ready)return;const c=fly.canvas,ctx=fly.ctx,w=c.clientWidth,h=c.clientHeight;if(fly.playing){fly.started=(t||0);fly.x=Math.sin((t||0)/2600)*.16;fly.y=Math.cos((t||0)/3300)*.07;fly.z=1+Math.sin((t||0)/2100)*.045;fly.yaw=Math.sin((t||0)/2800)*.035;fly.pitch=Math.cos((t||0)/3200)*.018;flyUpdateHud()}ctx.clearRect(0,0,w,h);ctx.fillStyle='#08110f';ctx.fillRect(0,0,w,h);const zoom=1/fly.z;const panX=fly.x*w,panY=fly.y*h;ctx.save();ctx.globalAlpha=.98;fitImage(ctx,fly.bg,w,h,zoom,panX,panY);ctx.restore();const pShiftX=panX-fly.yaw*w*1.5*fly.parallax,pShiftY=panY-fly.pitch*h*1.5*fly.parallax;ctx.save();ctx.globalAlpha=.98;fitImage(ctx,fly.person,w,h,zoom*1.012,pShiftX,pShiftY);ctx.restore();if(fly.lighting){const g=ctx.createRadialGradient(w*(.48+fly.x),h*(.3+fly.y),10,w*.5,h*.5,Math.max(w,h)*.75);g.addColorStop(0,'rgba(202,255,90,.10)');g.addColorStop(.55,'rgba(118,228,210,.035)');g.addColorStop(1,'rgba(0,0,0,.30)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h)}ctx.strokeStyle='rgba(202,255,90,.26)';ctx.beginPath();ctx.moveTo(w/2-24,h/2);ctx.lineTo(w/2+24,h/2);ctx.moveTo(w/2,h/2-24);ctx.lineTo(w/2,h/2+24);ctx.stroke()}
function flyToggle(){if(!fly.ready)return toast('Run an analysis first');fly.playing=!fly.playing;$('flyPlay').textContent=fly.playing?'Ⅱ Pause flythrough':'▶ Play flythrough';$('flyMode').textContent=fly.playing?'CINEMATIC PLAYBACK':'MANUAL CAMERA';if(fly.playing)fly.started=performance.now()}
$('flyPlay').onclick=flyToggle;$('flyReset').onclick=()=>{flyReset();toast('Flythrough camera reset')};$('flyLight').onclick=()=>{fly.lighting=!fly.lighting;$('flyLightState').textContent=fly.lighting?'ON':'OFF'};$('flyParallaxRange').oninput=e=>{fly.parallax=+e.target.value;flyUpdateHud()};$('flyFullscreen').onclick=()=>{$('flyWrap').requestFullscreen?.()||toast('Fullscreen is not supported in this browser')};$('flyWrap').addEventListener('pointerdown',e=>{if(!fly.ready)return;fly.drag=true;fly.lastX=e.clientX;fly.lastY=e.clientY;fly.playing=false;$('flyPlay').textContent='▶ Play flythrough';$('flyMode').textContent='MANUAL CAMERA';$('flyWrap').setPointerCapture?.(e.pointerId)});$('flyWrap').addEventListener('pointermove',e=>{if(!fly.drag)return;fly.yaw+=(e.clientX-fly.lastX)*.0015;fly.pitch=Math.max(-.3,Math.min(.3,fly.pitch+(e.clientY-fly.lastY)*.0015));fly.x=Math.max(-.35,Math.min(.35,fly.x+(e.clientX-fly.lastX)/800));fly.y=Math.max(-.25,Math.min(.25,fly.y+(e.clientY-fly.lastY)/800));fly.lastX=e.clientX;fly.lastY=e.clientY;flyUpdateHud()});['pointerup','pointercancel','pointerleave'].forEach(e=>$('flyWrap').addEventListener(e,()=>fly.drag=false));$('flyWrap').addEventListener('wheel',e=>{e.preventDefault();fly.z=Math.max(.72,Math.min(1.35,fly.z+e.deltaY*.0008));flyUpdateHud()},{passive:false});window.addEventListener('keydown',e=>{if(!fly.ready)return;const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown'].includes(k)){e.preventDefault();if(k==='arrowleft')fly.x-=.035;if(k==='arrowright')fly.x+=.035;if(k==='arrowup')fly.y-=.035;if(k==='arrowdown')fly.y+=.035;fly.x=Math.max(-.35,Math.min(.35,fly.x));fly.y=Math.max(-.25,Math.min(.25,fly.y));flyUpdateHud()}if(k==='r'&&document.activeElement?.tagName!=='INPUT')flyReset()});window.addEventListener('resize',flyResize);
'''
s=s.replace('</script></body></html>',flyjs+'</script></body></html>',1)
p.write_text(s)
print('flythrough patched')
